#!/bin/bash

first=1;

df | while read -r line; do
	
	if [[ $first -eq 1 ]]; then
                first=0
                continue
        fi


	if [[ $(echo "$line" | awk '{print $2}')  -lt 1000000 ]]; then
		echo "$line" | awk '{print $1 " " $2 " " $5}'
		continue
	fi

	if [[ $(echo "$line" | awk '{print $5}' | sed s/%//)  -gt 79 ]]; then
		echo "$line" | awk '{print $1 " " $2 " " $5}'
	fi


done 
